In [1]:
# importing necessary libraries
import pandas as pd
import numpy as np

In [2]:
# loading datasets
traffic_df = pd.read_csv("../data/raw/indian_smart_traffic_dataset_pro.csv")
air_df = pd.read_csv("../data/raw/realtime_air_quality_index.csv")

In [13]:
# previewing datasets
traffic_df.head()

,Timestamp,Day,Hour,Weather,Area_Type,Traffic_Density,Car_Count,Bike_Count,Truck_Count,Signal_Waiting_Time_Seconds
0,2025-09-26 17:03:00,Friday,17,Foggy,Industrial,Medium,32,46,9,37
1,2025-01-02 01:33:00,Thursday,1,Foggy,Residential,Low,18,17,5,5
2,2025-09-03 04:37:00,Wednesday,4,Clear,School Zone,Low,7,27,5,10
3,2025-11-18 01:30:00,Tuesday,1,Rainy,Commercial,Medium,34,49,13,46
4,2025-01-15 06:04:00,Wednesday,6,Foggy,Industrial,Low,5,18,5,16

In [4]:
air_df.head()

,country,state,city,station,last_update,latitude,longitude,pollutant_id,pollutant_min,pollutant_max,pollutant_avg
0,India,Bihar,Kishanganj,"SDM Office_Khagra, Kishanganj - BSPCB",03-03-2026 15:00:00,26.08813,87.938403,CO,17.0,22.0,21.0
1,India,Bihar,Motihari,"Gandak Colony, Motihari - BSPCB",03-03-2026 15:00:00,26.63086,84.900510,NO2,8.0,10.0,9.0
2,India,Bihar,Motihari,"Gandak Colony, Motihari - BSPCB",03-03-2026 15:00:00,26.63086,84.900510,SO2,3.0,3.0,3.0
3,India,Bihar,Motihari,"Gandak Colony, Motihari - BSPCB",03-03-2026 15:00:00,26.63086,84.900510,CO,36.0,46.0,40.0
4,India,Bihar,Motihari,"Gandak Colony, Motihari - BSPCB",03-03-2026 15:00:00,26.63086,84.900510,OZONE,3.0,5.0,4.0

In [14]:
# checking dimensions
traffic_df.shape

(15000, 10)

In [6]:
air_df.shape

(3329, 11)

In [15]:
# checking column names
traffic_df.columns

Index(['Timestamp', 'Day', 'Hour', 'Weather', 'Area_Type', 'Traffic_Density',
       'Car_Count', 'Bike_Count', 'Truck_Count',
       'Signal_Waiting_Time_Seconds'],
      dtype='object')

In [8]:
air_df.columns

Index(['country', 'state', 'city', 'station', 'last_update', 'latitude',
       'longitude', 'pollutant_id', 'pollutant_min', 'pollutant_max',
       'pollutant_avg'],
      dtype='object')

In [16]:
# checking datatypes
traffic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Timestamp                    15000 non-null  object
 1   Day                          15000 non-null  object
 2   Hour                         15000 non-null  int64
 3   Weather                      15000 non-null  object
 4   Area_Type                    15000 non-null  object
 5   Traffic_Density              15000 non-null  object
 6   Car_Count                    15000 non-null  int64
 7   Bike_Count                   15000 non-null  int64
 8   Truck_Count                  15000 non-null  int64
 9   Signal_Waiting_Time_Seconds  15000 non-null  int64
dtypes: int64(5), object(5)
memory usage: 1.1+ MB

In [10]:
air_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3329 entries, 0 to 3328
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   country        3329 non-null   object
 1   state          3329 non-null   object
 2   city           3329 non-null   object
 3   station        3329 non-null   object
 4   last_update    3329 non-null   object
 5   latitude       3329 non-null   float64
 6   longitude      3329 non-null   float64
 7   pollutant_id   3329 non-null   object
 8   pollutant_min  3195 non-null   float64
 9   pollutant_max  3195 non-null   float64
 10  pollutant_avg  3195 non-null   float64
dtypes: float64(5), object(6)
memory usage: 286.2+ KB

In [17]:
# checking missing values
traffic_df.isnull().sum()

Timestamp                      0
Day                            0
Hour                           0
Weather                        0
Area_Type                      0
Traffic_Density                0
Car_Count                      0
Bike_Count                     0
Truck_Count                    0
Signal_Waiting_Time_Seconds    0
dtype: int64

In [12]:
air_df.isnull().sum()

country            0
state              0
city               0
station            0
last_update        0
latitude           0
longitude          0
pollutant_id       0
pollutant_min    134
pollutant_max    134
pollutant_avg    134
dtype: int64

In [18]:
# checking duplicate rows
traffic_df.duplicated().sum()

np.int64(0)

In [19]:
air_df.duplicated().sum()

np.int64(0)

In [20]:
# basic statistics
traffic_df.describe()

,Hour,Car_Count,Bike_Count,Truck_Count,Signal_Waiting_Time_Seconds
count,15000.000000,15000.00000,15000.000000,15000.000000,15000.000000
mean,11.544600,35.63300,49.676600,10.370133,44.840533
std,6.903892,29.05259,35.872962,10.072479,43.892298
min,0.000000,5.00000,10.000000,0.000000,5.000000
25%,6.000000,14.00000,22.000000,3.000000,14.000000
50%,12.000000,26.00000,39.000000,7.000000,29.000000
75%,18.000000,46.00000,65.250000,14.000000,55.000000
max,23.000000,120.00000,150.000000,40.000000,180.000000

In [21]:
air_df.describe()

          latitude    longitude  pollutant_min  pollutant_max  pollutant_avg
count  3329.000000  3329.000000    3195.000000    3195.000000    3195.000000
mean     23.309351    78.595090      28.194992      95.054147      54.723005
std       5.071971     4.914670      31.950795      99.298276      55.009517
min       8.514909    70.776774       1.000000       1.000000       1.000000
25%      19.235581    75.387310       6.000000      20.000000      14.000000
50%      23.817487    77.287209      16.000000      64.000000      35.000000
75%      27.608912    80.891736      39.000000     124.000000      80.000000
max      34.066206    94.636574     257.000000     500.000000     393.000000

In [22]:
# checking unique values
traffic_df['Area_Type'].unique()

array(['Industrial', 'Residential', 'School Zone', 'Commercial',
       'Highway'], dtype=object)

In [23]:
traffic_df['Weather'].unique()

array(['Foggy', 'Clear', 'Rainy', 'Stormy', 'Cloudy'], dtype=object)

In [24]:
traffic_df['Traffic_Density'].unique()

array(['Medium', 'Low', 'High'], dtype=object)

In [25]:
air_df['city'].unique()

array(['Kishanganj', 'Motihari', 'Munger', 'Muzaffarpur', 'Visakhapatnam',
       'Naharlagun', 'Byrnihat', 'Guwahati', 'Kadapa',
       'Rajamahendravaram', 'Tirupati', 'Vijayawada', 'Begusarai',
       'Bettiah', 'Bhagalpur', 'Bihar Sharif', 'Buxar', 'Sivasagar',
       'Arrah', 'Aurangabad', 'Nagaon', 'Nalbari', 'Silchar', 'Gaya',
       'Hajipur', 'Katihar', 'Chhapra', 'Amaravati', 'Raipur', 'Tumidih',
       'Delhi', 'Sasaram', 'Siwan', 'Chandigarh', 'Bhilai', 'Chhal',
       'Korba', 'Kunjemura', 'Patna', 'Purnia', 'Saharsa', 'Ahmedabad',
       'Rajkot', 'Surat', 'Vadodara', 'Vapi', 'Vatva', 'Ambala', 'Jind',
       'Kaithal', 'Karnal', 'Kurukshetra', 'Mandikhera', 'Faridabad',
       'Fatehabad', 'Gurugram', 'Bahadurgarh', 'Bhiwani', 'Charkhi Dadri',
       'Ankleshwar', 'Bhavnagar', 'Gandhinagar', 'Mehsana', 'Dharuhera',
       'Manesar', 'Narnaul', 'Sirsa', 'Sonipat', 'Yamuna Nagar', 'Baddi',
       'Pampore', 'Srinagar', 'Bengaluru', 'Mysuru', 'Shivamogga',
       'Yadgir', 'Panchgaon', 'Panipat', 'Rohtak', 'Chikkaballapur',
       'Chikkamagaluru', 'Kalaburagi', 'Dharwad', 'Palwal', 'Gwalior',
       'Indore', 'Boisar', 'Chandrapur', 'Dhule', 'Jalgaon', 'Amravati',
       'Satna', 'Singrauli', 'Ahmednagar', 'Jabalpur', 'Katni',
       'Mandideep', 'Sagar', 'Kannur', 'Kollam', 'Thiruvananthapuram',
       'Badlapur', 'Belapur', 'Bhiwandi', 'Bhopal', 'Dewas', 'Mumbai',
       'Nagpur', 'Jalna', 'Kalyan', 'Kolhapur', 'Malegaon',
       'Mira-Bhayandar', 'Nanded', 'Solapur', 'Thane', 'Ulhasnagar',
       'Virar', 'Shillong', 'Parbhani', 'Pimpri-Chinchwad', 'Aizawl',
       'Kohima', 'Balasore', 'Navi Mumbai', 'Barbil', 'Baripada',
       'Bhubaneswar', 'Nashik', 'Pune', 'Byasanagar', 'Talcher',
       'Puducherry', 'Amritsar', 'Bathinda', 'Jalandhar', 'Ajmer',
       'Alwar', 'Banswara', 'Baran', 'Khanna', 'Ludhiana',
       'Mandi Gobindgarh', 'Patiala', 'Bhiwadi', 'Bikaner', 'Rourkela',
       'Suakati', 'Cuttack', 'Keonjhar', 'Nayagarh', 'Bharatpur',
       'Jaipur', 'Jaisalmer', 'Jalore', 'Jhalawar', 'Jhunjhunu',
       'Jodhpur', 'Chennai', 'Pali', 'Rajsamand', 'Sawai Madhopur',
       'Sikar', 'Sirohi', 'Dausa', 'Dholpur', 'Dungarpur', 'Karauli',
       'Kota', 'Bundi', 'Chittorgarh', 'Churu', 'Sri Ganganagar',
       'Gangtok', 'Nagaur', 'Coimbatore', 'Gummidipoondi', 'Perundurai',
       'Thoothukudi', 'Hyderabad', 'Agartala', 'Agra', 'Baghpat',
       'Bareilly', 'Firozabad', 'Lucknow', 'Ghaziabad', 'Gorakhpur',
       'Greater Noida', 'Muzaffarnagar', 'Noida', 'Meerut', 'Moradabad',
       'Jhansi', 'Kanpur', 'Prayagraj', 'Khurja', 'Varanasi', 'Vrindavan',
       'Kashipur', 'Rishikesh', 'Asansol', 'Barrackpore', 'Durgapur',
       'Haldia', 'Howrah', 'Kolkata', 'Siliguri', 'Araria', 'Tirumala',
       'Anantapur', 'Sri Vijaya Puram', 'Manguraha', 'Rajgir',
       'Samastipur', 'Milupara', 'Hisar', 'Ballabgarh', 'Ramanagara',
       'Vijayapura', 'Dhanbad', 'Chamarajanagar', 'Hubballi', 'Madikeri',
       'Damoh', 'Eloor', 'Ujjain', 'Akola', 'Pithampur', 'Latur', 'Mahad',
       'Sangli', 'Angul', 'Bileipada', 'Brajrajnagar', 'Rupnagar',
       'Tensa', 'Bhilwara', 'Rairangpur', 'Barmer', 'Tonk', 'Udaipur',
       'Pratapgarh', 'Hanumangarh', 'Bulandshahr', 'Hapur', 'Dehradun',
       'Chittoor', 'Bilaspur', 'Mangalore', 'Panchkula', 'Thrissur',
       'Ratlam', 'Raebareli'], dtype=object)

In [26]:
air_df['pollutant_id'].unique()

array(['CO', 'NO2', 'SO2', 'OZONE', 'PM2.5', 'NH3', 'PM10'], dtype=object)

In [39]:
# connecting mysql to notebook to pull data from mysql --> python
# installing the required library
!pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\devan\anaconda3\lib\site-packages (2.0.39)
Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\devan\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\devan\anaconda3\lib\site-packages (from sqlalchemy) (4.12.2)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.2

In [40]:
# another libraries
from sqlalchemy import create_engine

In [41]:
# creating mysql engine connection
engine = create_engine("mysql+pymysql://root:root@localhost/smart_city_analysis")

In [46]:
# loading traffic table into pandas
traffic_query = "SELECT * FROM traffic_data"
traffic_df = pd.read_sql(traffic_query, engine)

In [47]:
traffic_df.head()

,traffic_id,timestamp,day,hour,weather,area_type,traffic_density,car_count,bike_count,truck_count,signal_waiting_time_seconds
0,1,2025-09-26 17:03:00,Friday,17,Foggy,Industrial,Medium,32,46,9,37
1,2,2025-01-02 01:33:00,Thursday,1,Foggy,Residential,Low,18,17,5,5
2,3,2025-09-03 04:37:00,Wednesday,4,Clear,School Zone,Low,7,27,5,10
3,4,2025-11-18 01:30:00,Tuesday,1,Rainy,Commercial,Medium,34,49,13,46
4,5,2025-01-15 06:04:00,Wednesday,6,Foggy,Industrial,Low,5,18,5,16

In [48]:
air_query = "SELECT * FROM air_quality_data"
air_df = pd.read_sql(air_query, engine)
air_df.head()

,air_id,country,state,city,station,last_update,latitude,longitude,pollutant_id,pollutant_min,pollutant_max,pollutant_avg
0,1,India,Bihar,Kishanganj,"SDM Office_Khagra, Kishanganj - BSPCB",03-03-2026 15:00:00,26.088131,87.938403,CO,17,22,21
1,2,India,Bihar,Motihari,"Gandak Colony, Motihari - BSPCB",03-03-2026 15:00:00,26.630860,84.900510,NO2,8,10,9
2,3,India,Bihar,Motihari,"Gandak Colony, Motihari - BSPCB",03-03-2026 15:00:00,26.630860,84.900510,SO2,3,3,3
3,4,India,Bihar,Motihari,"Gandak Colony, Motihari - BSPCB",03-03-2026 15:00:00,26.630860,84.900510,CO,36,46,40
4,5,India,Bihar,Motihari,"Gandak Colony, Motihari - BSPCB",03-03-2026 15:00:00,26.630860,84.900510,OZONE,3,5,4

In [49]:
traffic_df.shape

(15000, 11)

In [50]:
air_df.shape

(3329, 12)