In [1]:
# importing required libraries
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

In [2]:
engine = create_engine("mysql+pymysql://root:root@localhost/smart_city_analysis")

In [3]:
traffic_df = pd.read_sql("SELECT * FROM traffic_data", engine)

In [38]:
air_df = pd.read_sql("SELECT * FROM air_quality_data", engine)

In [4]:
traffic_df.head()

,traffic_id,timestamp,day,hour,weather,area_type,traffic_density,car_count,bike_count,truck_count,signal_waiting_time_seconds
0,1,2025-09-26 17:03:00,Friday,17,Foggy,Industrial,Medium,32,46,9,37
1,2,2025-01-02 01:33:00,Thursday,1,Foggy,Residential,Low,18,17,5,5
2,3,2025-09-03 04:37:00,Wednesday,4,Clear,School Zone,Low,7,27,5,10
3,4,2025-11-18 01:30:00,Tuesday,1,Rainy,Commercial,Medium,34,49,13,46
4,5,2025-01-15 06:04:00,Wednesday,6,Foggy,Industrial,Low,5,18,5,16

In [39]:
air_df.head()

,air_id,country,state,city,station,last_update,latitude,longitude,pollutant_id,pollutant_min,pollutant_max,pollutant_avg
0,1,India,Bihar,Kishanganj,"SDM Office_Khagra, Kishanganj - BSPCB",03-03-2026 15:00:00,26.088131,87.938403,CO,17,22,21
1,2,India,Bihar,Motihari,"Gandak Colony, Motihari - BSPCB",03-03-2026 15:00:00,26.630860,84.900510,NO2,8,10,9
2,3,India,Bihar,Motihari,"Gandak Colony, Motihari - BSPCB",03-03-2026 15:00:00,26.630860,84.900510,SO2,3,3,3
3,4,India,Bihar,Motihari,"Gandak Colony, Motihari - BSPCB",03-03-2026 15:00:00,26.630860,84.900510,CO,36,46,40
4,5,India,Bihar,Motihari,"Gandak Colony, Motihari - BSPCB",03-03-2026 15:00:00,26.630860,84.900510,OZONE,3,5,4

In [6]:
traffic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   traffic_id                   15000 non-null  int64
 1   timestamp                    15000 non-null  datetime64[ns]
 2   day                          15000 non-null  object
 3   hour                         15000 non-null  int64
 4   weather                      15000 non-null  object
 5   area_type                    15000 non-null  object
 6   traffic_density              15000 non-null  object
 7   car_count                    15000 non-null  int64
 8   bike_count                   15000 non-null  int64
 9   truck_count                  15000 non-null  int64
 10  signal_waiting_time_seconds  15000 non-null  int64
dtypes: datetime64[ns](1), int64(6), object(4)
memory usage: 1.3+ MB

In [7]:
air_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3329 entries, 0 to 3328
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   air_id         3329 non-null   int64
 1   country        3329 non-null   object
 2   state          3329 non-null   object
 3   city           3329 non-null   object
 4   station        3329 non-null   object
 5   last_update    3329 non-null   object
 6   latitude       3329 non-null   float64
 7   longitude      3329 non-null   float64
 8   pollutant_id   3329 non-null   object
 9   pollutant_min  3329 non-null   object
 10  pollutant_max  3329 non-null   object
 11  pollutant_avg  3329 non-null   object
dtypes: float64(2), int64(1), object(9)
memory usage: 312.2+ KB

In [8]:
# checking missing values
traffic_df.isnull().sum()

traffic_id                     0
timestamp                      0
day                            0
hour                           0
weather                        0
area_type                      0
traffic_density                0
car_count                      0
bike_count                     0
truck_count                    0
signal_waiting_time_seconds    0
dtype: int64

In [40]:
air_df.isnull().sum()

air_id           0
country          0
state            0
city             0
station          0
last_update      0
latitude         0
longitude        0
pollutant_id     0
pollutant_min    0
pollutant_max    0
pollutant_avg    0
dtype: int64

In [10]:
# drop duplicates
traffic_df = traffic_df.drop_duplicates()
air_df = air_df.drop_duplicates()

In [14]:
traffic_df.duplicated().sum()

np.int64(0)

In [41]:
air_df.duplicated().sum()

np.int64(0)

In [16]:
# converting traffic timestamp to datetime
traffic_df['timestamp'] = pd.to_datetime(traffic_df['timestamp'])

In [17]:
traffic_df.dtypes

traffic_id                              int64
timestamp                      datetime64[ns]
day                                    object
hour                                    int64
weather                                object
area_type                              object
traffic_density                        object
car_count                               int64
bike_count                              int64
truck_count                             int64
signal_waiting_time_seconds             int64
dtype: object

In [42]:
# converting air quality date column
air_df['last_update'] = pd.to_datetime(
    air_df['last_update'],
    dayfirst=True,
    errors='coerce'
)

In [43]:
air_df.dtypes

air_id                    int64
country                  object
state                    object
city                     object
station                  object
last_update      datetime64[ns]
latitude                float64
longitude               float64
pollutant_id             object
pollutant_min            object
pollutant_max            object
pollutant_avg            object
dtype: object

In [20]:
# converting pollutant columns to numeric
air_df['pollutant_min'] = pd.to_numeric(air_df['pollutant_min'], errors='coerce')
air_df['pollutant_max'] = pd.to_numeric(air_df['pollutant_max'], errors='coerce')
air_df['pollutant_avg'] = pd.to_numeric(air_df['pollutant_avg'], errors='coerce')

In [26]:
air_df.dtypes

air_id                    int64
country                  object
state                    object
city                     object
station                  object
last_update      datetime64[ns]
latitude                float64
longitude               float64
pollutant_id             object
pollutant_min           float64
pollutant_max           float64
pollutant_avg           float64
dtype: object

In [21]:
# handling missing pollutant values
air_df[['pollutant_min', 'pollutant_max', 'pollutant_avg']].isnull().sum()

pollutant_min    134
pollutant_max    134
pollutant_avg    134
dtype: int64

In [44]:
air_df.isnull().sum()

air_id           0
country          0
state            0
city             0
station          0
last_update      0
latitude         0
longitude        0
pollutant_id     0
pollutant_min    0
pollutant_max    0
pollutant_avg    0
dtype: int64

In [32]:
# replacing the missing values with median
air_df['pollutant_min'] = air_df['pollutant_min'].fillna(air_df['pollutant_min'].median())
air_df['pollutant_max'] = air_df['pollutant_max'].fillna(air_df['pollutant_max'].median())
air_df['pollutant_avg'] = air_df['pollutant_avg'].fillna(air_df['pollutant_avg'].median())

In [33]:
air_df[['pollutant_min','pollutant_max','pollutant_avg']].isnull().sum()

pollutant_min    0
pollutant_max    0
pollutant_avg    0
dtype: int64

In [45]:
air_df

,air_id,country,state,city,station,last_update,latitude,longitude,pollutant_id,pollutant_min,pollutant_max,pollutant_avg
0,1,India,Bihar,Kishanganj,"SDM Office_Khagra, Kishanganj - BSPCB",2026-03-03 15:00:00,26.088131,87.938403,CO,17,22,21
1,2,India,Bihar,Motihari,"Gandak Colony, Motihari - BSPCB",2026-03-03 15:00:00,26.630860,84.900510,NO2,8,10,9
2,3,India,Bihar,Motihari,"Gandak Colony, Motihari - BSPCB",2026-03-03 15:00:00,26.630860,84.900510,SO2,3,3,3
3,4,India,Bihar,Motihari,"Gandak Colony, Motihari - BSPCB",2026-03-03 15:00:00,26.630860,84.900510,CO,36,46,40
4,5,India,Bihar,Motihari,"Gandak Colony, Motihari - BSPCB",2026-03-03 15:00:00,26.630860,84.900510,OZONE,3,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...
3324,3325,India,West_Bengal,Kolkata,"Rabindra Sarobar, Kolkata - WBPCB",2026-03-03 15:00:00,22.511060,88.351420,CO,28,111,39
3325,3326,India,West_Bengal,Kolkata,"Victoria, Kolkata - WBPCB",2026-03-03 15:00:00,22.544808,88.340369,PM10,72,193,139
3326,3327,India,West_Bengal,Kolkata,"Victoria, Kolkata - WBPCB",2026-03-03 15:00:00,22.544808,88.340369,CO,38,109,47
3327,3328,India,West_Bengal,Kolkata,"Victoria, Kolkata - WBPCB",2026-03-03 15:00:00,22.544808,88.340369,OZONE,8,89,62
3328,3329,India,West_Bengal,Siliguri,"Ward-32 Bapupara, Siliguri - WBPCB",2026-03-03 15:00:00,26.687923,88.415250,PM2.5,44,117,81

In [46]:
# save the cleaned data
traffic_df.to_csv("../data/processed/traffic_cleaned.csv", index=False)
air_df.to_csv("../data/processed/air_quality_cleaned.csv", index=False)